name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🟢 Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: 📦 Install dependencies
        run: npm ci

      - name: 🧹 Lint JavaScript
        run: npm run lint

      - name: 🎨 Lint SCSS
        run: npm run lint:scss

      - name: 🧼 Check Prettier formatting
        run: npm run format -- --check
